#!/bin/bash

# Please make note of the NOW_TOKEN environment variable. 
# This allows us to interact with now from the build server.
# Investigate the --token flag.

# Research how to generate a token with Zeit and create
#+ an environment variable in Travis CI with the Zeit token as the value.
#+ The NOW_TOKEN contains the token generated by Zeit and exposed on the Travis Server.
now public --token=$NOW_TOKEN